name: Build, Squash and Push Stack Image

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The release version number'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Install docker-squash
        run: |
          if ! command -v docker-squash &> /dev/null; then
            pip install docker-squash
          fi

      - name: Build Docker image (before squashing)
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          docker build \
            --build-arg RELEASE_VERSION=${{ github.event.inputs.release_version }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:${{ github.event.inputs.release_version }} \
            .

      - name: Squash Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:${{ github.event.inputs.release_version }}
          LATEST_IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:latest
          
          # Get the layer to squash from (excluding the last layer)
          LAYER_COUNT=$(docker history $IMAGE_NAME | wc -l | xargs)
          LAYER_TO_SQUASH_FROM=$(($LAYER_COUNT - 1))

          docker save $IMAGE_NAME | docker-squash -f $LAYER_TO_SQUASH_FROM -t $IMAGE_NAME
          
          docker tag $IMAGE_NAME $LATEST_IMAGE_NAME

      - name: Push Docker image with tags
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:${{ github.event.inputs.release_version }}
          LATEST_IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:latest
          docker push $IMAGE_NAME
          docker push $LATEST_IMAGE_NAME
